name: Deploy

on:
  push:
    branches:
      - master

jobs:
  pre-commit:
    uses: './.github/workflows/ci.yml'
  build:
    needs: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "nestjs-react-boilerplate"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
